###################################################
#
# Makefile
# Author: Methodios Zacharioudakis
#
###################################################

all: 		antivirus

antivirus: 	antivirus.c
		gcc antivirus.c -o antivirus -lssl -lcrypto -lcurl

clean:
		rm -f antivirus
		clear
